package.path = "res/script/?.lua;"..package.path
require "unity"
local scene = GetScene()
scene:SetBackground(1)
scene:AddActor(1)
local actor1 = scene:GetActor(1)
actor1:SetPos(100,200)
actor1:SetAction(3,2)
scene:AddActor(2)
local actor2 = scene:GetActor(2)
actor2:SetPos(200,100)
actor2:SetAction(1,4)
scene:AddActor(3)
local actor3 = scene:GetActor(3)
actor3:SetPos(200,200)
scene:PushAction(3,eAction_Walk,4,0,4)
local num = scene:GetCurrentNum()
scene:PushAction(1,eAction_Shout,3,200,0,num)
scene:PushAction(2,eAction_Cry,1,400,0,num)
scene:PushWords(1,"曹操","哈哈哈哈")
scene:PushAction(3,eAction_Walk,3,0,4)